# Generated by Django 3.2.4 on 2021-06-29 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewdeftoken',
            name='expireDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 18, 57, 30, 767211)),
        ),
        migrations.AddField(
            model_name='sewdeftoken',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
